server:
  port: 8080

spring:
  application:
    name: api-gateway
  profiles:
    active: local

  cloud:
    loadbalancer:
      configurations: default
      cache:
        enabled: true
        ttl: 35s
      health-check:
        initial-delay: 0
        interval: 25s

    gateway:
      routes:

        # Review Service Routes
        - id: review-service-user-reviews
          uri: ${services.review-service.url}
          predicates:
            - Path=/api/users/*/reviews/**
          filters:
            - StripPrefix=0

        # Order Service Routes
        - id: order-service-user-orders
          uri: ${services.order-service.url}
          predicates:
            - Path=/api/users/*/orders/**
          filters:
            - StripPrefix=0

        - id: order-service-global
          uri: ${services.order-service.url}
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=0

        # GENERAL ROUTES LAST

        # User Service Routes (MUST be after specific /users/* routes)
        - id: user-service
          uri: ${services.user-service.url}
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=0

        # Product Service Routes - Load Balancing
        - id: product-service-categories
          uri: lb://product-service
          predicates:
            - Path=/api/categories/**
          filters:
            - StripPrefix=0

        - id: product-service-products
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=0

        # Cart Service Routes - Load Balancing
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/api/users/*/cart/**
          filters:
            - StripPrefix=0

      # Global CORS configuration
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"

# Default service URLs (localhost - for local development)
services:
  user-service:
    url: http://localhost:8081
  order-service:
    url: http://localhost:8084
  review-service:
    url: http://localhost:8085

# Configuration custom pour définir l'algorithme
#loadbalancer:
#  algorithm:
#    product-service: round-robin  # Options: round-robin, random, weighted
#    cart-service: round-robin

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway,prometheus
  endpoint:
    gateway:
      enabled: true