server:
  port: 8080

spring:
  application:
    name: api-gateway
  profiles:
    active: local  # Default profile

  cloud:
    gateway:
      routes:
        # SPECIFIC ROUTES FIRST - Order matters!

        # Review Service Routes
        - id: review-service-user-reviews
          uri: ${services.review-service.url}
          predicates:
            - Path=/api/users/*/reviews/**
          filters:
            - StripPrefix=0

        - id: review-service-product-reviews
          uri: ${services.review-service.url}
          predicates:
            - Path=/api/products/*/reviews/**
          filters:
            - StripPrefix=0

        # Cart Service Routes
        - id: cart-service
          uri: ${services.cart-service.url}
          predicates:
            - Path=/api/users/*/cart/**
          filters:
            - StripPrefix=0

        # Order Service Routes
        - id: order-service-user-orders
          uri: ${services.order-service.url}
          predicates:
            - Path=/api/users/*/orders/**
          filters:
            - StripPrefix=0

        - id: order-service-global
          uri: ${services.order-service.url}
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=0

        # GENERAL ROUTES LAST

        # User Service Routes (MUST be after specific /users/* routes)
        - id: user-service
          uri: ${services.user-service.url}
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=0

        # Product Service Routes
        - id: product-service-categories
          uri: ${services.product-service.url}
          predicates:
            - Path=/api/categories/**
          filters:
            - StripPrefix=0

        - id: product-service-products
          uri: ${services.product-service.url}
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=0

      # Global CORS configuration
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"

# Default service URLs (localhost - for local development)
services:
  user-service:
    url: http://localhost:8081
  product-service:
    url: http://localhost:8082
  cart-service:
    url: http://localhost:8083
  order-service:
    url: http://localhost:8084
  review-service:
    url: http://localhost:8085

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway,prometheus
  endpoint:
    gateway:
      enabled: true